project:
  type: website
  resources: 
    - "*.pdf"


website:
  title: "HusterCourses"
  favicon: NLFavicon.png
  sidebar:
    style: docked
    search: true
    collapse-level: 1
    contents: auto
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



